### ISSUE TITLE
Winpty hangs when launched from ConEmu

### ISSUE THREAD

**Issue by eugenesvk** [rprichard/winpty#70] opened 2016-04-06 15:27 UTC
I've build MPV from MSYS2 [MINGW package](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-mpv) on Windows 10 wiht `msys/winpty 0.2.2-1 [installed]` default MSYS package and whenever I try to launch the default mpv script placed in my `\mingw64\bin\` folder:
```
#!/usr/bin/env bash
export _started_from_console=yes
/usr/bin/winpty "$( dirname ${BASH_SOURCE[0]} )/mpv.exe" "$@"
```
nothing happens, it just hangs up and doesn't even respond to `^C` breaks (well, maybe nothing hangs, it's just doing something invisible and ignores breaks). When I use `mpv.exe` directly, it all works fine either.

Since I don't really understand the role of `winpty` when using MPV I'm not sure whether I can just remove this script and use `mpv.exe` directly or should fix this issue somehow and continue to use the script.

**Comment by rprichard** [comment] 2016-04-06 17:00
I suppose it shouldn't hang.  If removing winpty from the command-line works, then I imagine that invoking mpv.exe directly would work fine, for you at least.  On my Ubuntu machine, `mpv` displays status updates to my terminal, and the same key commands work in both the terminal and the video window.  However, I can use `mpv` to play an audio file, in which case there is no video window.

If you run `mpv.exe` in a mintty terminal, does the command-line work properly?  (e.g. Pressing `[` and `]` should adjust playback speed.)

If you run `mpv.exe` in a Windows console, the command-line ought to work properly, and adding `winpty` to the command-line should be unnecessary but mostly harmless.

Is there an easy way for me to build MPV?  I tried:

```
rprichard@VBWIN7 MSYS ~/winpty-build
$ git clone https://github.com/Alexpux/MINGW-packages.git
Cloning into 'MINGW-packages'...
remote: Counting objects: 34547, done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 34547 (delta 51), reused 2 (delta 2), pack-reused 34309
Receiving objects: 100% (34547/34547), 18.52 MiB | 2.28 MiB/s, done.
Resolving deltas: 100% (16973/16973), done.
Checking connectivity... done.
Checking out files: 100% (3114/3114), done.

rprichard@VBWIN7 MSYS ~/winpty-build
$ cd MINGW-packages/mingw-w64-mpv/

rprichard@VBWIN7 MSYS ~/winpty-build/MINGW-packages/mingw-w64-mpv
$ makepkg
==> ERROR: pkgname is not allowed to start with a hyphen.
```

**Comment by eugenesvk** [comment] 2016-04-06 17:21
> If you run mpv.exe in a mintty terminal, does the command-line work properly? (e.g. Pressing [ and ] should adjust playback speed.)

Yes, `mpv.exe` it works fine in my mintty terminal as well as in windows console

Re.  your hyphen error it's because for some weird reason the `${MINGW_PACKAGE_PREFIX}` variable in that place is not read from the environment even if it's set. But the thing is — it's not set in the default MSYS2 installation, I had to set it manually to `mingw-w64-x86_64`, realize that it doesn't work anyway and hardcode `mingw-w64-x86_64` to `PKGBUILD`
The other variable `${MINGW_PREFIX}` should also be set in your environment to `/MINGW64` (strangly enough, this var CAN be read from the environment and doesn't require hard coding the value)

By the way, running from windows console also hangs
`\path\to\usr\bin\winpty.exe \path\to\msys64\mingw64\bin\mpv.exe  \path\to\mp4`

**Comment by eugenesvk** [comment] 2016-04-06 21:26
After resolving https://github.com/rprichard/winpty/issues/69 it now works in windows console with the same keybinds active in both video window and console window, which is nice!
It still hangs when I use it MSYS2 consoles (Mintty or ConEmu connector), but I don't understand whether it's a bug or not. If not, do you know how I can prioritize `mpv.exe` over `mpv` shell script so I don't have to type `.exe` every time I invoke `mpv` from MSYS2 consoles?

**Comment by rprichard** [comment] 2016-04-06 22:24
I think the fix is: change the wrapper script to run `mpv.com` rather than `mpv.exe`.

Details:

The difference between `winpty` and `winpty-git` is strictly an MSYS2 packaging thing.  i.e. It's downstream, whereas I'm upstream.  It looks like `winpty` uses a source archive, whereas `winpty-git` clones my git repo.  Seems like a good idea.  I think the switch happened about 3 weeks ago.

I'm actually unable to run `pacman -S mingw-w64-x86_64-mpv`, because that package depends on `winpty-git`, but now my MSYS2 environment is using the `winpty` package.  I still haven't figured out how to compile mpv in the MSYS2 environment, so instead I downloaded the `mpv-x86_64-20160229` prebuilt binary mentioned at https://mpv.io/installation/.

That package has `mpv.com` and `mpv.exe` binaries.  Both binaries are non-Cygwin/non-MSYS2 Windows executables.  `mpv.com` is a CONSOLE executable, whereas `mpv.exe` is a GUI executable.  (It's breaking the ordinary convention where a COM file is a simplified MS-DOS executable, which is neat.)  Console programs are intended to be run a command-line, whereas GUI programs are intended to be run from the Windows Explorer.  If a GUI program is run from `cmd.exe`, `cmd.exe` doesn't wait for the program to finish before prompting for more commands, which makes interaction difficult.

It seems like `mpv.exe` doesn't interact with a console, even if you run it in a way that waits for it to exit.  There are various methods for that:

 * from a cmd.exe prompt: `start /wait mpv.exe C:/Windows/Performance/WinSAT/WinSAT.wmv`
 * from any MSYS2/Cygwin bash prompt: `./mpv.exe C:/Windows/Performance/WinSAT/WinSAT.wmv`
 * from any Cygwin bash prompt: `cygstart --wait ./mpv.exe C:/Windows/Performance/WinSAT/WinSAT.wmv`
 * from a MSYS2/Cygwin mintty prompt: `winpty ./mpv.exe C:/Windows/Performance/WinSAT/WinSAT.wmv`

In all cases, MPV doesn't respond to keyboard input in the terminal or console.  e.g. It does nothing when I hit Ctrl-C.  I also don't see any input.

(A similar thing happens if you run Notepad using an above method.  The Notepad window appears, but Ctrl-C at the terminal/console doesn't kill Notepad.)

You definitely want to run `mpv.com` rather than `mpv.exe`, because MSYS2 (and Cygwin) behave like Unix, where the terminal interacts with the GUI program.  You still want to use winpty if you're using mintty, because it dramatically improves the UX.  (If you're running `mpv.com` inside a normal Windows console or inside ConEmu, then you don't need winpty, but it shouldn't hurt.)

**Comment by eugenesvk** [comment] 2016-04-06 22:35
>unable to run `pacman -S mingw-w64-x86_64-mpv` ... now my MSYS2 environment is using the winpty package

I just manually built this package https://github.com/Alexpux/MSYS2-packages/tree/master/winpty-git and upon installation it replaced `winpty`

Thank you for clarification on com vs exe, the old MS-DOS convention was confusing me (I'm glad they broke it though )


> You still want to use winpty if you're using mintty

Ok, would be happy to, but it hangs :( so I'm just using `mpv.com` everywhere until can fix it.

**Comment by rprichard** [comment] 2016-04-06 23:45
By building and installing winpty-git from source, I was able to install `mingw-w64-x86_64-mpv` via pacman, but the resulting binaries didn't work at all.  They needed DLLs that didn't exist.  Given that those binaries require a newly non-existent winpty-git package, I'm not very interested in them.

I also tried building the MSYS2 mpv package.  I opened a MINGW64 environment.  (e.g. `/mingw64/bin` is on the PATH).  Then I ran makepkg-mingw` rather than `makepkg`.  Apparently the MinGW-specific tool sets the `MINGW_PACKAGE_PREFIX` variable.  However, this produced an `mpv` binary that ran, but spit out errors like so:
```
rprichard@ATOM-W10 MINGW64 ~
$ /mingw64/bin/mpv /c/Windows/Performance/WinSAT/WinSAT.wmv
Playing: C:\Windows\Performance\WinSAT\WinSAT.wmv
 (+) Video --vid=1 (wmv3)
File tags:
 Title: WSAT_Fountains
VO: [opengl] 1280x720 yuv420p
[vo/opengl] shader link log (status=0): Failed to create D3D shaders.
[vo/opengl]
[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
V: 00:00:00 / 00:00:06 (0%)
[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
V: 00:00:00 / 00:00:06 (1%)
[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
V: 00:00:00 / 00:00:06 (2%)
[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
V: 00:00:00 / 00:00:06 (2%)
[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
V: 00:00:00 / 00:00:06 (3%)
[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
V: 00:00:00 / 00:00:06 (10%)
[vo/opengl] shader link log (status=0): Failed to create D3D shaders.
[vo/opengl]
V: 00:00:02 / 00:00:06 (34%)


Exiting... (Quit)
```
The video window appeared, and the playback time updated in the terminal, but the window was black.

I tried using the `mpv` wrapper script with the https://mpv.io binaries, and they work.  I found the source to what I think is `mpv.com` ([link](https://github.com/mpv-player/mpv/blob/master/osdep/win32-console-wrapper.c)), and it looks like `mpv.com` just executes `mpv.exe` with  `_started_from_console=yes`, more or less.  So, the wrapper script should be fine as-is.

I'd suggest downloading the mpv.io binary, installing `winpty` from pacman, then running this in mintty:
```
_started_from_console=yes winpty mpv-x86_64-20160229/mpv.exe c:/Windows/Performance/WinSAT/WinSAT.wmv
```

When you say that winpty "hangs", are you at least able to see a video playback window?

**Comment by rprichard** [comment] 2016-04-07 00:12
FWIW, I did all my testing above using a Windows 10 installed on real hardware, but when I run the https://mpv.io binaries on a Win7 VM, I never see a window appear.  On real hardware, if I run `mpv.exe` from the Explorer, I'll see a window appear asking me to drop a file into it.  In the VM, `mpv.exe` starts, and I can see it in the Task Manager, but that's it.

**Comment by eugenesvk** [comment] 2016-04-07 00:35
> When you say that winpty "hangs", are you at least able to see a video playback window?

Nope, the playback window doesn't get opened, I only have `winpty` process that doesn't do its job.

> resulting binaries didn't work at all

Yeah, pacman version is also outdated `0.14.0-1` vs `0.16.0-1`

> `makepkg-mingw` rather than `makepkg`

Hm, you're right. I wrongly assumed that it was all handled via env vars and built all my packages with just `makepkg` running from MinGW shell. That's an unnecessary complication on MSYS2 parth, but oh well. Anyway, it should've mattered since I set the env vars myself that pointed to the same folders/files.

I've rebuilt and reinstalled it your way. However, I still can't run the `/mingw64/bin/mpv /c/path/to/vid` command, it hangs again.
When I use `mpv.exe` or `.com` it's all fine, I don't get the error you get (maybe it's specific to your video card or something or maybe your default settings should be adjusted).

**Comment by eugenesvk** [comment] 2016-04-07 00:42
Nope, installing default pacman `winpty` and executing `_started_from_console=yes winpty /e/mpv-x86_64-20160229/mpv.exe /c/Users/Evgeny/Videos/mkv.mkv`

**Comment by rprichard** [comment] 2016-04-07 01:09
Huh, not sure what's up then.  The next things I'd try would be:

 * Run `winpty-debugserver.exe` in another MSYS terminal, then run the mpv command again with the `WINPTY_DEBUG=trace` variable set.  Output [like this](https://gist.github.com/rprichard/255c3b77acf997c7230ca08d242a927a) should appear in the debugserver terminal.  The video path I've given is 7 seconds long; if you wait 7 seconds, does the command exit?  There's a 7-second gap between "CreateProcess: success 4976" where mpv.exe is spawned, and "Closing data pipe after child exit" where mpv.exe exits.

 * Run the same command with the `WINPTY_SHOW_CONSOLE=1` environment variable set.  With that variable, the underlying console is visible.  When I run it, this text appears in a new console window (and the time updates):

    ```
    Playing: C:\Windows\Performance\WinSAT\WinSAT.wmv
     (+) Video --vid=1 (wmv3)
    File tags:
     Title: WSAT_Fountains
    VO: [opengl] 1280x720 yuv420p
    V: 00:00:05 / 00:00:06 (99%)


    Exiting... (End of file)
    ```

**Comment by eugenesvk** [comment] 2016-04-07 01:12
Your second option at least doesn't hang my console, I get a window appearing for a split second (can't see what's inside), then it closes and outputs `Error creating winpty.`

**Comment by rprichard** [comment] 2016-04-07 01:24
FWIW, I was referring to this video, which I mentioned earlier, c:/Windows/Performance/WinSAT/WinSAT.wmv.  It seems to be on Win7 and Win10 machines already by default.

**Comment by rprichard** [comment] 2016-04-07 01:33
> In the first option I can get output from the debugserver only if I interrupt it since the second terminal hangs and doesn't finish

Funny you mention that.  I noticed today that running `/mingw64/bin/windres` reliably hangs the MSYS2 mintty, but only in the MINGW64 shell.  In the MINGW32 or MSYS shells, that command immediately prints `C:\msys64\mingw64\bin\windres.exe: preprocessing failed.`.

**Comment by eugenesvk** [comment] 2016-04-07 01:55
In MSYS2 Mintty shell second option still fails with the same error.
First option:
I get an extra tab in addition to the perma-running 2nd terminal
2nd terminal still doesn't finish
However, when `^C` the first debug terminal the status message is different
```
[93878.650 winpty.exe,p1764,t1244]: Created agent successfully, pid=2212, cmdline="C:\Dev\msys64\usr\bin\winpty-agent.exe" \\.\pipe\winpty-1764-1-1d1906ffa594e8b-8bc49261dbc0ea4f6ac77e0ed2af7c08-control \\.\pipe\winpty-1764-1-1d1906ffa594e8b-8bc49261dbc0ea4f6ac77e0ed2af7c08-data 123 17
[93878.788 winpty-agent.exe,p7840,t4872]: Agent starting...
[93878.789 winpty-agent.exe,p7840,t4872]: setSmallFont: attempting to set a small font (CP=437 OutputCP=437)
[93878.789 winpty-agent.exe,p7840,t4872]: previous font: nFont=0 dwFontSize=(6,10) FontFamily=0x36 FontWeight=400 FaceName=Lucida Console (4C 75 63 69 64 61 20 43 6F 6E 73 6F 6C 65)
```

**Comment by eugenesvk** [comment] 2016-04-07 01:59
When I run with ConEmu connector (MINGW64) now I get debugger output in realtime (don't have to `^C` to get it)

```
[94166.246 winpty.exe,p7716,t5620]: Created agent successfully, pid=1956, cmdline="C:\Dev\msys64\usr\bin\winpty-agent.exe" \\.\pipe\winpty-7716-1-1d19070a5c4e759-9fa9a0ff771508a3cbccd2b350896294-control \\.\pipe\winpty-7716-1-1d19070a5c4e759-9fa9a0ff771508a3cbccd2b350896294-data 139 19
```

However, it still hangs with no output :(

**Comment by eugenesvk** [comment] 2016-04-07 02:01
Man, I do hope Windows gets that promised Ubuntu update very soon — it's such a pain in the ass to troubleshoot all this stuff.

**Comment by rprichard** [comment] 2016-04-07 02:14
`winpty-debugserver` flushes its output after every line, so you shouldn't ever have to Ctrl-C it to get output.  Killing other processes with Ctrl-C also shouldn't display more output.  If you're having trouble finding a reliable terminal/console to run `winpty-debugserver.exe`, just run it from a plain old console (e.g. Start -> Run -> `cmd.exe`), or just redirect its output to a file.

It's matter a lot whether the debugserver is only printing one line versus four lines.  Four lines is a bizarre result -- why would it stop after printing `previous font: ...` but not continue to `previous font table: ...`.  If that's really what's happening, that's actually a good clue.

**Comment by eugenesvk** [comment] 2016-04-07 02:19
> so you shouldn't ever have to Ctrl-C it to get output.

That's exactly what I expected, and yet it only works with the ConEmu connector, not in Mintty, which is supposed to be *nix-native-like (that's the only reason I'm using it in troubleshooting)

I have no idea what's going on there with one line in one terminals and four lines in another

**Comment by rprichard** [comment] 2016-04-07 02:36
`winpty-debugserver.exe` should work fine without any other third-party shells, console emulators, etc.  It's not a Cygwin/MSYS program and has no MinGW dependencies, so it even runs from the Windows Explorer.

If the debugserver is run from the Explorer, how many lines of output are there?  Is it reliably 4?

**Comment by eugenesvk** [comment] 2016-04-07 02:55
> It's not a Cygwin/MSYS program

Ok, thanks for clarifying

When running from windows console it gives one line
```
[97527.236 winpty.exe,p5296,t6704]: Created agent successfully, pid=8692, cmdline="C:\Dev\msys64\usr\bin\winpty-agent.exe" \\.\pipe\winpty-5296-1-1d190787913559c-b9727860b1f54c72697ac2ecbd3b1436-control \\.\pipe\winpty-5296-1-1d190787913559c-b9727860b1f54c72697ac2ecbd3b1436-data 124 17
```

**Comment by rprichard** [comment] 2016-04-07 03:12
When it hangs, is the `winpty-agent.exe` process still running?

**Comment by rprichard** [comment] 2016-04-07 03:19
Oh, I should also ask: can you run winpty with *other* programs, like PowerShell?

**Comment by rprichard** [comment] 2016-04-07 04:15
And, if you *can* run `winpty powershell`, then what does `winpty-debugserver` output?

**Comment by eugenesvk** [comment] 2016-04-07 06:10
> When it hangs, is the winpty-agent.exe process still running?

Well, I don't actually see the `winpty-agent.exe` process in my task manager, only see `winpty.exe` — not even when I start the command.

>And, if you can run winpty powershell, then what does winpty-debugserver output?

Same thing 
```
[09112.650 winpty.exe,p1556,t11408]: Created agent successfully, pid=5432, cmdline="C:\Dev\msys64\usr\bin\winpty-agent.exe" \\.\pipe\winpty-1556-1-1d19093728518ef-e47f1ffcf31d31b9b562c3d3eef08757-control \\.\pipe\winpty-1556-1-1d19093728518ef-e47f1ffcf31d31b9b562c3d3eef08757-data 140 19
```

**Comment by rprichard** [comment] 2016-04-07 06:24
Ok, so if I understand correctly, it has nothing to do with mpv?  `winpty.exe` starts the agent process, and the agent process immediately dies, for some reason.

If you set `WINPTY_DEBUG=trace` and also `WINPTY_SHOW_CONSOLE=1`, what does `winpty powershell` output in the debugserver?

**Comment by eugenesvk** [comment] 2016-04-07 06:41
Yes, you seem to be correct, nothing to do with mpv (glad we found this out!)
Running `export WINPTY_DEBUG=trace; export WINPTY_SHOW_CONSOLE=1; winpty powershell.exe` creates a new blank `winpty-agent.exe` window and debugserver shows the following 

```
[11078.552 winpty.exe,p14692,t15112]: Created agent successfully, pid=11644, cmdline="C:\Dev\msys64\usr\bin\winpty-agent.exe" \\.\pipe\winpty-14692-1-1d190980649dc2f-863444ce7aff02a2b7ae6b0f2e0f230c-control \\.\pipe\winpty-14692-1-1d190980649dc2f-863444ce7aff02a2b7ae6b0f2e0f230c-data 124 17
[11078.709 winpty-agent.exe,p1548,t6140]: Agent starting...
[11078.711 winpty-agent.exe,p1548,t6140]: setSmallFont: attempting to set a small font (CP=437 OutputCP=437)
[11078.713 winpty-agent.exe,p1548,t6140]: previous font: nFont=0 dwFontSize=(6,10) FontFamily=0x36 FontWeight=400 FaceName=Lucida Console (4C 75 63 69 64 61 20 43 6F 6E 73 6F 6C 65)
```

**Comment by rprichard** [comment] 2016-04-07 06:45
Are you running that winpty command inside ConEmu?  I'm doing some testing with ConEmu, and I've noticed that (1) it's injecting `ConEmuHk64.dll` into some of its child processes, and (2) it's affecting how `winpty powershell.exe` behaves.  It still *mostly* works--I just have to hit Enter after Powershell has exited to make winpty exit.  That shouldn't happen, so I'm looking into it.

**Comment by eugenesvk** [comment] 2016-04-07 07:17
Yes, finally! You're correct, running from ConEmu was indeed causing an issue! Thank you.
I'm excited that you've finally found the issue! Though ConEmu is my main terminal app, so would be nice if you could find out why it's breaking your app so it can be fixed.

**Comment by rprichard** [comment] 2016-04-07 07:36
I'm glad we got that figured out!  :)

I'm looking over the source code to ConEmuHk -- it's kinda impressive in terms of how much of the Windows API surface it's hooking.

My first observation is that winpty's [`readFontTable()`](https://github.com/rprichard/winpty/blob/25076e51a7c7460202b3665924a168147dc67b07/src/agent/ConsoleFont.cc#L275) can hang when ConEmu hooks `OnGetConsoleFontSize`[[1]](https://github.com/Maximus5/ConEmu/blob/8f81c1aa9ec97a4709c5e13412eb12221622cfb0/src/ConEmuHk/hkConsole.cpp#L572)[[2]](https://github.com/Maximus5/ConEmu/blob/8f81c1aa9ec97a4709c5e13412eb12221622cfb0/src/ConEmuHk/hlpConsole.cpp#L54).  It isn't well-documented, but there is a small finite table of font sizes, and winpty is expecting the GetConsoleFontSize() call to eventually fail once the index is too big.  That probably explains the case where the debugserver printed only four lines.  `readFontTable()` is only called when trace output is enabled or when running on XP.

There really needs to be a convenient way to wrap a program with winpty, but only when stdin/stdout/stderr are *not* already consoles.  If that method existed, the ConEmu<->winpty incompatibility wouldn't matter much.  ConEmu's Cygwin connector would probably still break things.

**Comment by eugenesvk** [comment] 2016-04-07 07:54
> My first observation is that winpty's readFontTable()

That was fast! Unfortunately that goes well beyond my level of expertise. If you find something that ConEmu needs to fix, would you kindly coordinate with @Maximus5 directly?
I'm mostly using the MSYS2 connector (it's a separate one from Cygwin, by the way) though since it's much more convenient than Mintty, e.g. I couldn't even convince the Mintty dev to look into implementing simple `Ctrl+C/V` to copy/paste optional remappings)

Thanks again for your responsiveness and help in debugging this issue!

**Comment by Maximus5** [comment] 2016-04-07 08:03
The connector has not been released to public ConEmu distro because it was not finished yet:

1. Connector have to be started automatically by ConEmu when user run cygwin/msys application.
2. Connector should be "paused" when user starts not cygwin/msys application from cygwin/msys shell.

I want to say, that winpty wouldn't be used in these use cases.

**Comment by rprichard** [comment] 2016-04-07 08:20
For correctness, perhaps ConEmu should never hook the winpty agent, somehow.

From an efficiency standpoint, winpty wrapping is certainly pointless if the user is already using a Windows console, which includes environments that use a console underneath, such as ConEmu, Console2, or winpty itself.

I get the impression that, with the connector, stdin/stdout/stderr are Cygwin ptys, but when the Cygwin process spawns a non-Cygwin process, the ConEmu hooks will make I/O still work somehow?  Perhaps the child will think it's connected to a console?  I tried it recently, and PowerShell had some trouble with it, and my `winpty-agent --show-input` diagnostic program decided that it wasn't connected to a console.

In any case, I opened #73 to consider the idea that winpty wrapper scripts should not involve winpty if the user is already using a console.  I suspect it should also detect the ConEmu connector somehow.

**Comment by Maximus5** [comment] 2016-04-07 08:26
I don't think that ConEmu must not hook winpty. On the contrary, ConEmu must hook any console application to avoid weird bugs and support features. Must known example - `-new_console` switch.

**Comment by rprichard** [comment] 2016-04-07 09:29
`winpty.dll` spawns the agent process in a new, hidden console window.  (Technically it's on a background window station, but I intend to also make it `SW_HIDE` sometime.)  I'm thinking that perhaps ConEmu doesn't have any reason to hook the agent process.

That is:

 * If I'm not using ConEmu as the default terminal, then ConEmu could exempt `CREATE_NEW_CONSOLE` processes.

 * If I *am* using ConEmu as the default terminal, then ConEmu could still exempt processes that hide their console windows.

In either case, I'm not sure why ConEmu would need to hook the process.

I've noticed that ConEmu already doesn't hook all children processes.  For example... if I run `start cmd` from a ConEmu window (Cmd1), then ConEmu hooks the new cmd process (Cmd2), evidenced by the green prompt.  If I then run a `cmd` child (Cmd3) inside the new console window, ConEmu *doesn't* hook Cmd3, as evidenced by the visible escape sequences.  Why doesn't it?  Maybe it's not hooked because ConEmu has figured out that Cmd2's console wasn't under ConEmu control?

I'm going to add `SW_HIDE` to the agent `STARTUPINFO` just in case that affects whether it's hooked.

**Comment by rprichard** [comment] 2016-04-07 09:33
> If I am using ConEmu as the default terminal, then ConEmu could still exempt processes that hide their console windows.

Or maybe not, actually.  Does ConEmu have a mode where it tries to hook *every* process, so it can catch any process that opens a new, visible console window?

**Comment by Maximus5** [comment] 2016-04-07 09:50
No need to spawn new hidden RealConsole window, because RealConsole window already exists in ConEmu.
Moreover, `winpty.dll` can't spawn new RealConsole, because process **can't** have more than a one RealConsole in Windows.

ConEmu DefTerm doesn't affect (theoretically) GUI processes started from ConEmu consoles, and CUI processes, if they are started "detached" from ConEmu.

However, it hooks every process in ConEmu's consoles, and may be (I'm not sure, have to be checked) even CUI processes started detached from ConEmu, because user expect that ConEmu terminal would be used for spawned applications.

Anyway, I believe that winpty wouldn't be useful in ConEmu at all, because all thing are planned to be working from the box, automatically.

**Comment by rprichard** [comment] 2016-04-07 10:14
> No need to spawn new hidden RealConsole window, because RealConsole window already exists in ConEmu.

That's https://github.com/rprichard/winpty/issues/73.  From the standpoint of `winpty.dll`, though, the presence of ConEmu doesn't really matter.  e.g. A command-line program with `ConEmuHk64.dll` loaded in it could accept a network connection and use `winpty.dll` to connect that network socket to a new, invisible console.  Yes, the network server has a "RealConsole", but it's irrelevant.

> Moreover, winpty.dll can't spawn new RealConsole, because process can't have more than a one RealConsole in Windows.

`winpty.dll` spawns `winpty-agent.exe`, and the new agent process is attached to a new console (using `CREATE_NEW_CONSOLE`).  A program running `winpty.dll` can spawn as many agents as it wants.

> Anyway, I believe that winpty wouldn't be useful in ConEmu at all, because all thing are planned to be working from the box, automatically.

Agreed, more or less.  The `winpty.exe` Cygwin adapter is much less useful if a Windows CUI program can run under ConEmu and successfully do console I/O using console APIs.  Comes back to https://github.com/rprichard/winpty/issues/73.

> ConEmu DefTerm doesn't affect (theoretically) GUI processes started from ConEmu consoles, and CUI processes, if they are started "detached" from ConEmu.

What do you mean by "detached"?  I tried `start cmd` in ConEmu, and the new `cmd.exe` process is hooked, even without DefTerm.  If I then run `cmd.exe`, inheriting that new console window, the new `cmd.exe` process is not hooked.  Maybe if a ConEmu console starts a CUI process with `CREATE_NEW_CONSOLE`, that new CUI process shouldn't be hooked?

Anyway, I tried adding `SW_HIDE` to the agent's `STARTUPINFO`, and it did prevent ConEmu from hooking the agent process, so that change should reduce the likelihood that ConEmu breaks winpty.  I had other reasons to use `SW_HIDE` anyway (i.e. https://github.com/rprichard/winpty/issues/58).

**Comment by Maximus5** [comment] 2016-04-07 10:31
DefTerm has no effect on console processes started console processes.
All processes spawned in the ConEmu consoles are to be hooked. But when CreateProcess is used to start new RealConsole, in some cases (SW_HIDE and SW_MINIMIZE) ConEmu do not attach the process to new ConEmu tab.

**Comment by rprichard** [comment] 2016-04-07 10:55
> All processes spawned in the ConEmu consoles are to be hooked.

GUI processes and CUI processes spawned as `SW_HIDE` are exceptions, right?

I just find it strange that ConEmu would want to hook a process spawned with a new console, if it has no intention of adopting that console.  What's the rationale?

FWIW: The `mpv.exe` process discussed above is actually a GUI process, so it's spawned without an attached console.  When the `_started_from_console` environment variable is `yes`, it reattaches to the console of its parent process.  Ergo, during playback, it writes to the ConEmu console without being hooked by ConEmu.  I'm not sure how this affects things one way or another.

**Comment by rprichard** [comment] 2016-04-08 01:52
@eugenesvk What version of ConEmu and MSYS2 connector are you using?

I'm using:
 * ConEmu 160403a [64]
 * ConEmu cygwin/msys connector version 0.7.4

FWIW: I can't currently reproduce an actual incompatibility between ConEmu and winpty.  (I thought I saw a minor problem involving PowerShell, but now I can't reproduce it.)  From the notes above, there seem to be two places where winpty is hanging:

 * In `readFontTable()`, where the agent would hang if the ConEmu hook were ignoring the font index for `GetConsoleFontSize`.  I *think* that would happen if ConEmu attached to the agent's console at agent startup, but I can't get ConEmu to attach.  (ConEmu hooks the agent process, but it doesn't take over its console window.)

 * After `winpty.dll` starts the agent process, but before the agent prints the `Agent starting...` message, apparently?  I don't know how that could happen.  Maybe the agent process is actually dying instantly, and `winpty.exe` is hanging, because it's waiting for the agent to connect to its pipes.

**Comment by eugenesvk** [comment] 2016-04-09 17:42
I'm using the exact same versions

**Comment by rprichard** [comment] 2016-04-09 19:50
The issue only reproduces when ConEmu's `ProcessCmdStart` flag is enabled.  It's in `Features` -> `Process 'start'`.  With that flag, ConEmu adopts windows started with the `start` command.  I suspect the behavior is more general, and it's trying to adopt the agent's new console and failing.  Merely injecting the hook DLL into the agent doesn't cause this bug.

FWIW, I also tried attaching ConEmu to a visible agent console (i.e. `WINPTY_SHOW_CONSOLE=1`), and it only worked if I selected "Alternate Mode".  By default, it failed with the error, `Failed to start console server in the remote process`.

The Cygwin/MSYS connector is irrelevant; the hang reproduces without it.

With `WINPTY_SHOW_CONSOLE=1` and `WINPTY_DEBUG=trace`, winpty gets stuck after printing `previous font:`, as already reported above.  There is another ConEmu tab, `winpty-agent`, which is blank.  It's presumably stuck in `readFontTable()`, and the agent's memory use is steadily climbing, as expected.

Adding the `SW_HIDE` flag to `STARTUPINFO` fixes the winpty bug.

@Maximus5 I added a trace() line as the first line in the agent's `main()` function, and I didn't see the trace output.  `winpty.dll` reports that `CreateProcess` successfully started the agent, but the agent process isn't running.  Due to the hooking, `winpty.dll` spawned `ConEmuC64.exe` instead of `winpty-agent.exe`, but it seems that `ConEmuC64.exe` exited without starting the agent process.  Apparently, if a CUI program tries to spawn another CUI program in a different window station, then the spawn fails.  I think that's a ConEmu bug.

**Comment by rprichard** [comment] 2016-04-09 20:01
I bet `ConEmuC64.exe` is starting on the child's desktop, and then it's failing because it's using HWND values from the parent desktop.

**Comment by rprichard** [comment] 2016-04-10 23:09
The hanging issue is fixed now, and the ConEmu and winpty combination works as long as winpty's real console stays hidden.

There's still a ConEmu<->winpty incompatibility when `WINPTY_SHOW_CONSOLE=1` is set on Windows Vista and up, and when ConEmu is configured with "Process 'start'" enabled.  ConEmu hooks `CreateProcess` such that `winpty.dll` starts a ConEmu executable instead, and then that executable starts `winpty-agent.exe`.  `winpty.dll` notices that the process connecting to its pipes has the wrong PID.  That's annoying, but `WINPTY_SHOW_CONSOLE=1` is only for debugging.

**Closed by rprichard** 2016-04-10 23:09 UTC
Labels: bug
