### ISSUE TITLE
[Feature Request] A New Stable Release

### ISSUE THREAD

**Issue by leycec** [rprichard/winpty#32] opened 2015-08-13 07:44 UTC
The [most recent release](https://github.com/rprichard/winpty/releases/tag/release-0.1.1) appears to be over three years old, whereas the [most recent commit](https://github.com/rprichard/winpty/commit/9a9c148043f84cab8db68466b2e6a321fe36dcd3) appears to be less than a year old. Maybe it's just me, but... There seems to be a discrepancy here.

Given that the 0.1.1 release is probably tragically broken in several painful ways (e.g., 64-bit support), it'd be great to get an 0.1.2 or (preferably) 0.2 release at some point. **No rush,** of course. I'm happy to just `git clone` up the live codebase. But an official release _would_ probably simplify CLI life for others.

As well as demonstrate that this project is still alive and kicking! :high_heel:

**Comment by rprichard** [comment] 2015-08-13 07:57
Yeah, the project needs some attention.  Part of the problem is that I don't actively use it day-to-day.  I'm in the middle of a cross-country move, so I'm unlikely to look at it in the next week.  I'll try to make some time, though, after I'm settled in.

**Comment by leycec** [comment] 2015-08-13 08:25
**Excellent.**

Thanks to the native Windows magic that is the Miniconda Python distribution, I _do_ actively use `winpty`.

For that reason, you should know that `winpty` is brilliant. Where once I ran either `cygstart python` or `python -i` and bled endless tears of unadulterated frustration (..._a lucrative autobiography title_), I now run `console python` and pump my fist with childlike triumph. It just works. Which is more than I can say for 99% of the Cygwin Experience<sup>TM</sup>.

Best of luck in your long haul! May the hippie spirit of the West Coast indwell in you always.

Yes, I'll stop spamming now.

**Comment by rprichard** [comment] 2015-11-14 02:48
I've created an 0.2.0 tag and GitHub release, with release notes and five binary tarballs covering Cygwin 32-bit/64-bit, MSYS 32-bit, and MSYS2 32-bit/64-bit.  (I have a script that automatically makes the tarballs, so future releases should remain easy to produce.)

AFAIK, this issue is fixed now.  I'll reopen it if there's something wrong with the release.  (But if there were, I suppose I'd just make a new release anyway.)

**Closed by rprichard** 2015-11-14 02:48 UTC
Labels: enhancement
